#  $Date$
#  $Id$
#	 $Name$
#	 $Log$
#	 $State$

#LIBC=LIBC6
LIBC=LIBC5


#ifeq ($(LIBC),LIBC6)
CC=gcc
#else
#CC = i486-linuxlibc1-gcc	
#endif

#CC=checkergcc

CFLAGS=-I../ -D$(LIBC) -c -D_GNU_SOURCE -s

LD=ld
LDFLAGS=-L/usr/lib

all: sakide

sakide:
	$(CC) $(CFLAGS) -o sakide.static.o sakide.c
	$(LD) $(LDFLAGS) -o sakide.static sakide.static.o

